fun main() {
    println()
    println("Ejemplo para Cola:")
    println()
    var cola = Cola(4)
    println("Verifiquemos que nuestra pila creada está vacia --> ${cola.estaVacia()}")
    println("->  Encolamos los valores 13, 21, 2 y 9...")
    cola.encolar(13)
    cola.encolar(21)
    cola.encolar(2)
    cola.encolar(9)
    println("Así quedó nuestra cola --> ${cola.toString()} Su primer elemento es --> ${cola.primero()}")
    println("Verifiquemos si nuestra cola luego de agregar elementos esta vacia --> ${cola.estaVacia()}")
    println("->  Probemos encolando un elemento adicional... (No debería encolar)")
    cola.encolar(5)
    println("->  No agregó debido a que pasó a su máximo de elementos -> Probemos desencolar...")
    cola.desencolar()
    println("->  Acabamos de desencolar al primer elemento de la cola --> ${cola.toString()}")
    println("El primer elemento es ahora --> ${cola.primero()} -> Desencolemos todos los elementos...")
    cola.desencolar()
    println("--> ${cola.toString()}")
    cola.desencolar()
    println("--> ${cola.toString()}")
    cola.desencolar()
    println("--> ${cola.toString()}")
    println("Listo! Verifiquemos que nuestra lista está vacia --> ${cola.estaVacia()}")
    println("->  Probemos descolar un elemento adicional... (No debería descolar)")
    cola.desencolar()
    println("No descoló debido a que la cola no posee más elementos.")

    println()
    println("Ejemplo para Pila:")
    println()

    var pila = Pila(4)
    println("Verifiquemos que nuestra pila creada está vacia --> ${pila.estaVacia()}")
    println("->  Empilamos los valores 33, 65, 74, 100...")
    pila.empilar(33)
    pila.empilar(65)
    pila.empilar(74)
    pila.empilar(150)
    println("Así quedó nuestra pila --> ${pila.toString()} Su ultimo elemento es --> ${pila.tope()}")
    println("Verifiquemos si nuestra pila luego de agregar elementos esta vacia --> ${pila.estaVacia()}")
    println("->  Probemos empilar un elemento adicional... (No debería agregar)")
    pila.empilar(545)
    println("->  No agregó debido a que pasó a su máximo de elementos -> Probemos desempilar...")
    pila.desempilar()
    println("->  Acabamos de desempilar el ultimo elemento de la pila --> ${pila.toString()}")
    println("El ultimo elemento es ahora --> ${pila.tope()} -> Desempilamos todos los elementos...")
    pila.desempilar()
    println("--> ${pila.toString()}")
    pila.desempilar()
    println("--> ${pila.toString()}")
    pila.desempilar()
    println("--> ${pila.toString()}")
    println("Listo! Verifiquemos que nuestra pila está vacia --> ${pila.estaVacia()}")
    println("->  Probemos desempilar un elemento adicional... (No debería quitar mas elementos)")
    pila.desempilar()
    println("No desempiló debido a que la pila no posee mas elementos.")
}